import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { test } from "node:test";

const preview = readFileSync(new URL("../src/lib/design/align-preview.ts", import.meta.url), "utf8");
const stage = readFileSync(new URL("../src/components/studio/canvas-stage.tsx", import.meta.url), "utf8");
const inspector = readFileSync(new URL("../src/components/studio/inspector.tsx", import.meta.url), "utf8");
const keys = readFileSync(new URL("../src/components/studio/use-shortcuts.ts", import.meta.url), "utf8");

test("align preview draws the key edge before commit", () => {
  assert.match(preview, /export function planAlign/);
  assert.match(preview, /export function drawAlignPreview/);
  assert.match(preview, /First click previews the phosphor edge/);
  assert.match(preview, /expandMovePlaces/);
  assert.match(preview, /"stay" : "key"/);
  assert.match(preview, /keyName/);
  assert.match(preview, /plan\.keyName/);
  assert.match(inspector, /data-align-key-name/);
  assert.match(preview, /plan\.edge} edge/);
  assert.match(preview, /export function placeAlignEdgeChip/);
  assert.match(preview, /clear of stay boxes/);
  assert.match(preview, /alignEdgeChipLabel/);
  assert.match(preview, /\$\{plan\.edge\} · \$\{who\}/);
  assert.match(preview, /hang the longer/);
  assert.match(preview, /plan\.edge === "left"/);
  assert.match(preview, /plan\.edge === "bottom"/);
  assert.match(preview, /export function placeAlignStayStamp/);
  assert.match(preview, /stay box corner/);
  assert.match(preview, /stamp\.label/);
  assert.match(preview, /edge === "middle"/);
  assert.match(preview, /edge === "center"/);
  assert.match(preview, /export function holdAlignCommitEcho/);
  assert.match(preview, /export function drawAlignCommitEcho/);
  assert.match(preview, /export function alignCommitEchoAlpha/);
  assert.match(preview, /eases to 0/);
  assert.match(preview, /ctx.globalAlpha = alpha/);
  assert.match(preview, /stamp holds on/);
  assert.match(preview, /edge tick fades with it/);
  assert.match(preview, /export function placeAlignCommitEdgeTick/);
  assert.match(preview, /held\.edgeTick/);
  assert.match(preview, /placeAlignStayStamp\(g, held\.edge, zoom\)/);
  assert.match(stage, /drawAlignCommitEcho\(ctx, alignEcho, viewport\.zoom/);
  assert.match(preview, /export function placeAlignCommitEdgeCaption/);
  assert.match(preview, /caption if stamp crops names key or board and fades with the stamp/);
  assert.match(preview, /releases with the beat/);
  assert.match(preview, /paintAlignEdgeCaption\(ctx, caption, z, alpha\)/);
  assert.match(preview, /chipLabel/);
  assert.match(preview, /stampsOff && chipLabel \? chipLabel : edge/);
  assert.match(preview, /held\.chipLabel/);
  assert.match(preview, /repeats the preview pill/);
  assert.match(preview, /visible end of the commit tick/);
  assert.match(preview, /caption\.label/);
  assert.match(preview, /export function placeAlignPreviewEdgeCaption/);
  assert.match(preview, /edge caption if chip crops/);
  assert.match(preview, /repeats the chip pill/);
  assert.match(preview, /chipOff \? alignEdgeChipLabel\(plan\) : plan\.edge/);
  assert.match(preview, /names key or board/);
  assert.match(preview, /visible end of the preview tick/);
  assert.match(preview, /paintAlignEdgeCaption/);
  assert.match(stage, /drawAlignPreview\(ctx, alignPreview, viewport\.zoom, \{/);
  assert.match(keys, /clearAlignCommitEcho\(\)/);


  assert.match(stage, /drawAlignPreview\(ctx, alignPreview, viewport\.zoom, \{/);
  assert.match(inspector, /Align to key/);
  assert.match(inspector, /data-align-edge/);
  assert.match(inspector, /data-align-stay/);
  assert.match(inspector, /data-align-move/);
  assert.match(inspector, /data-align=/);
  assert.match(inspector, /Commit left/);
  assert.match(inspector, /Align to board/);
  assert.match(inspector, /data-align-board=/);
  assert.match(inspector, /data-align-target=\{target\}/);
  assert.match(inspector, /data-align-target-chip=\{target\}/);
  assert.match(preview, /export function planAlignBoard/);
  assert.match(preview, /Aligned \$\{plan\.edge\} to \$\{plan\.target === "board" \? "board" : plan\.keyName\}/);
  assert.match(keys, /commitAlignPreview\(\)/);
  assert.match(keys, /clearAlignPreview\(\)/);
});

test("board left edge shifts a box onto x 0 and pins a box already there", () => {
  const board = { x: 0, w: 200 };
  const mover = { x: 40, w: 20 };
  const stay = { x: 0, w: 10 };
  assert.equal(board.x - mover.x, -40);
  assert.equal(board.x - stay.x, 0);
  assert.match(preview, /target: "board"/);
  assert.match(preview, /Align to board needs an unlocked layer/);
  assert.match(preview, /board edge/);
});

test("left edge keeps the key and shifts the other box", () => {
  const key = { id: "key", x: 40, y: 10, w: 20, h: 20 };
  const other = { id: "other", x: 0, y: 30, w: 10, h: 8 };
  const dx = key.x - other.x;
  assert.equal(dx, 40);
  assert.equal(other.x + dx, key.x);
  assert.match(preview, /key stays/);
  assert.match(preview, /Aligned \$\{plan\.edge\} to \$\{plan\.target === "board" \? "board" : plan\.keyName\}/);
});
