import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { test } from "node:test";

const preview = readFileSync(new URL("../src/lib/design/align-preview.ts", import.meta.url), "utf8");
const stage = readFileSync(new URL("../src/components/studio/canvas-stage.tsx", import.meta.url), "utf8");
const inspector = readFileSync(new URL("../src/components/studio/inspector.tsx", import.meta.url), "utf8");
const layers = readFileSync(new URL("../src/components/studio/layers-panel.tsx", import.meta.url), "utf8");
const keys = readFileSync(new URL("../src/components/studio/use-shortcuts.ts", import.meta.url), "utf8");
const studio = readFileSync(new URL("../src/components/studio/studio-app.tsx", import.meta.url), "utf8");

test("align preview draws the key edge before commit", () => {
  assert.match(preview, /export function planAlign/);
  assert.match(preview, /export function drawAlignPreview/);
  assert.match(preview, /First click previews the phosphor edge/);
  assert.match(preview, /expandMovePlaces/);
  assert.match(preview, /"stay" : "key"/);
  assert.match(preview, /keyName/);
  assert.match(preview, /plan\.keyName/);
  assert.match(inspector, /data-align-key-name/);
  assert.match(inspector, /alignEdgeChipLabel/);
  assert.match(inspector, /data-align-preview-chip=\{alignEdgeChipLabel\(live\)\}/);
  assert.match(inspector, /data-align-preview-line/);
  assert.match(inspector, /Same chip as the layers row/);
  assert.match(preview, /plan\.edge} edge/);
  assert.match(preview, /export function placeAlignEdgeChip/);
  assert.match(preview, /clear of stay boxes/);
  assert.match(preview, /alignEdgeChipLabel/);
  assert.match(preview, /\$\{plan\.edge\} · \$\{who\}/);
  assert.match(preview, /hang the longer/);
  assert.match(preview, /plan\.edge === "left"/);
  assert.match(preview, /plan\.edge === "bottom"/);
  assert.match(preview, /export function placeAlignStayStamp/);
  assert.match(preview, /stay box corner/);
  assert.match(preview, /stamp\.label/);
  assert.match(preview, /edge === "middle"/);
  assert.match(preview, /edge === "center"/);
  assert.match(preview, /export function holdAlignCommitEcho/);
  assert.match(preview, /export function drawAlignCommitEcho/);
  assert.match(preview, /export function alignCommitEchoAlpha/);
  assert.match(preview, /eases to 0/);
  assert.match(preview, /ctx.globalAlpha = alpha/);
  assert.match(preview, /stamp holds on/);
  assert.match(preview, /edge tick fades with it/);
  assert.match(preview, /export function placeAlignCommitEdgeTick/);
  assert.match(preview, /held\.edgeTick/);
  assert.match(preview, /placeAlignStayStamp\(g, held\.edge, zoom\)/);
  assert.match(stage, /drawAlignCommitEcho\(ctx, alignEcho, viewport\.zoom/);
  assert.match(preview, /export function placeAlignCommitEdgeCaption/);
  assert.match(preview, /caption if stamp crops names key or board and fades with the stamp/);
  assert.match(preview, /export function noteAlignCommitFadeCaption/);
  assert.match(preview, /alignCommitFadeAppend\(pill, echo.moveCount\)/);
  assert.match(preview, /fade \$\{pill\} · \$\{moveCount\} move/);
  assert.match(preview, /strip reads \$\{chip\}/);
  assert.match(preview, /const chip = alignEdgeChipLabel\(plan\)/);
  assert.match(studio, /StudioStatusStrip/);
  assert.match(preview, /baseStatus/);
  assert.match(preview, /fadingPill/);
  assert.match(preview, /rail and the strip agree/);
  assert.match(preview, /fadePill/);
  assert.match(preview, /moveCount: boxes.length/);
  assert.match(inspector, /data-align-commit-line/);
  assert.match(inspector, /data-align-commit-pill/);
  assert.match(inspector, /echo.fadePill/);
  assert.match(preview, /moverIds/);
  assert.match(preview, /each mover's layers row/);
  assert.match(layers, /data-layer-align-pill/);
  assert.match(layers, /alignEcho\?\.moverIds.includes/);
  assert.match(layers, /subscribeAlignCommitEcho/);
  assert.match(preview, /export function alignPreviewMoverIds/);
  assert.match(preview, /Stay rows stay unmarked/);
  assert.match(layers, /subscribeAlignPreview/);
  assert.match(layers, /alignPreviewMoverIds\(alignPreview\)/);
  assert.match(layers, /data-layer-align-preview=/);
  assert.match(layers, /data-layer-align-preview-mover/);
  assert.match(layers, /alignEdgeChipLabel\(alignPreview\)/);
  assert.match(layers, /Edge chip while align preview is armed/);
  assert.match(inspector, /alignCommitLayerFadeLine\(echo.chipLabel, echo.fadePill, echo.moveCount\)/);
  assert.match(inspector, /data-align-commit-chip=\{echo.chipLabel\}/);
  assert.match(inspector, /alignCommitSolidLead\(echo.chipLabel, echo.moveCount\)/);
  assert.match(inspector, /Same truncated chip and move count the status strip leads with/);
  assert.match(preview, /alignCommitSolidLead/);
  assert.match(preview, /\$\{lead\} · Aligned · strip reads \$\{chipLabel\}/);
  assert.match(layers, /alignCommitSolidLead\(alignEcho\.chipLabel, alignEcho\.moveCount\)/);
  assert.match(layers, /alignCommitLayerFadeLine/);
  assert.match(layers, /data-layer-align-fade/);
  assert.match(preview, /export function alignCommitLayerFadeLine/);
  assert.match(preview, /each mover row keeps/);
  assert.match(inspector, /The fade pill can still append after it/);
  assert.match(inspector, /appends the cropped pill with the same move count the layers row and status strip show/);
  assert.match(preview, /export function alignCommitFadeAppend/);


  assert.match(preview, /releases with the beat/);
  assert.match(preview, /paintAlignEdgeCaption\(ctx, caption, z, alpha\)/);
  assert.match(preview, /chipLabel/);
  assert.match(preview, /stampsOff && releaseLine \? releaseLine : stampsOff && chipLabel \? chipLabel : edge/);
  assert.match(preview, /alignCommitLayerFadeLine\(held\.chipLabel, held\.chipLabel, held\.moveCount\)/);
  assert.match(preview, /repeats the same release line/);
  assert.match(preview, /wider than the rail/);
  assert.match(preview, /shrinks the type or wraps once rather than clipping the move count/);
  assert.match(preview, /only partly on the rail still names the full line/);
  assert.match(preview, /function fitAlignCommitCaption/);
  assert.match(preview, /function wrapReleaseLineOnce/);
  assert.match(preview, /function seatWrappedCommitCaption/);
  assert.match(preview, /seats clear of the landed boxes/);
  assert.match(preview, /status strip keeps the unwrapped release line/);
  assert.match(preview, /function openCropEndAlong/);
  assert.match(preview, /rail clamp pulls that two-line pill back onto a short mover/);
  assert.match(preview, /slides to the open end of the crop so the move count stays off the art/);
  assert.match(preview, /both crop ends are blocked/);
  assert.match(preview, /tucks the move-count line into the nearest gap beside the short mover/);
  assert.match(preview, /function tuckMoveCountBesideShortMover/);
  assert.match(preview, /tuckedMoveCount/);
  assert.match(preview, /When that gap sits off the rail, the tucked line pins to the crop edge nearest that mover/);
  assert.match(preview, /function pinTuckedCountToNearestCropEdge/);
  assert.match(preview, /function swapPinnedCountOffSharedCropEdge/);
  assert.match(preview, /share the crop edge nearest the short mover/);
  assert.match(preview, /swaps the count to the other crop edge so the two lines do not stack/);
  assert.match(preview, /function slideSwappedCountAlongBlockedEdge/);
  const swappedDoc = preview.slice(
    preview.indexOf("When the swapped move-count line lands on a blocked other crop edge"),
    preview.indexOf("function slideSwappedCountAlongBlockedEdge"),
  );
  assert.match(swappedDoc, /sharing a span with an eighth stay stamp on that edge/);
  assert.match(swappedDoc, /sharing a span with a twelfth stay stamp on that edge/);
  assert.match(swappedDoc, /The walk stops at twelve so a full row/);
  assert.match(swappedDoc, /Same twelve-step stay-stamp walk the slid/);
  assert.match(preview, /Same twelve-step stay-stamp walk the slid line uses. Stops at twelve so a full row clears/);
  assert.match(preview, /function dropSwappedCountOffSharedLeadSpan/);
  assert.match(preview, /still stacks the swapped move-count line on the lead after the twelve-step walk/);
  assert.match(preview, /drop the count one caption-height off that shared vertical span/);
  assert.match(preview, /no longer read as one stack/);
  assert.match(preview, /one-caption drop still shares a vertical span with the lead because the crop clamp held it in the band/);
  assert.match(preview, /step one more caption-height off that shared span/);
  assert.match(preview, /at\(step \* 2\)/);
  assert.match(preview, /function slideCountAlongCropEdgeClearOfLead/);
  assert.match(preview, /Second caption-height drop, when the extra step is also clamped inside the lead band/);
  assert.match(preview, /slides the move-count line along the crop edge into the nearest gap that no longer shares a vertical span with the lead/);
  assert.match(preview, /Prefer the seat just outside the lead band closest to the count/);
  assert.match(preview, /function tuckCountOneCaptionWidthOffEdgeBesideLead/);
  assert.match(preview, /function stepCountOneMoreCaptionWidthOffEdgeBesideLead/);
  assert.match(preview, /function stepCountSecondCaptionWidthOffEdgeBesideLead/);
  assert.match(preview, /function stepCountThirdCaptionWidthOffEdgeBesideLead/);
  assert.match(preview, /function stepCountFourthCaptionWidthOffEdgeBesideLead/);
  assert.match(preview, /function stepCountFifthCaptionWidthOffEdgeBesideLead/);
  assert.match(preview, /function stepCountSixthCaptionWidthOffEdgeBesideLead/);
  assert.match(preview, /stepCountThirdCaptionWidthOffEdgeBesideLead\(zoom, crop, lead, steppedAgain\)/);
  assert.match(preview, /stepCountFourthCaptionWidthOffEdgeBesideLead\(zoom, crop, lead, steppedThird\)/);
  assert.match(preview, /stepCountFifthCaptionWidthOffEdgeBesideLead\(zoom, crop, lead, steppedFourth\)/);
  assert.match(preview, /stepCountSixthCaptionWidthOffEdgeBesideLead\(zoom, crop, lead, steppedFifth\)/);
  assert.match(preview, /step one more caption-width off the edge into the next gap beside the lead/);
  assert.match(preview, /the lead is wider than that step so the count still covers the lead/);
  assert.match(preview, /Second caption-width step, when the lead is still wider than that step so the count covers the lead/);
  assert.match(preview, /that second caption-width still covers the lead because the lead is wider than that step/);
  assert.match(preview, /Third caption-width step, when the second extra step still covers the lead because the lead is wider than that step/);
  assert.match(preview, /that third caption-width still covers the lead because the lead is wider than that step/);
  assert.match(preview, /Fourth caption-width step, when the third extra step still covers the lead because the lead is wider than that step/);
  assert.match(preview, /that fourth caption-width still covers the lead because the lead is wider than that step/);
  assert.match(preview, /Fifth caption-width step, when the fourth extra step still covers the lead because the lead is wider than that step/);
  assert.match(preview, /that fifth caption-width still covers the lead because the lead is wider than that step/);
  assert.match(preview, /Sixth caption-width step, when the fifth extra step still covers the lead because the lead is wider than that step/);
  assert.match(preview, /that sixth caption-width still covers the lead because the lead is wider than that step/);
  assert.match(preview, /Seventh caption-width step, when the sixth extra step still covers the lead because the lead is wider than that step/);
  assert.match(preview, /that seventh caption-width still covers the lead because the lead is wider than that step/);
  assert.match(preview, /function stepCountSeventhCaptionWidthOffEdgeBesideLead/);
  assert.match(preview, /Eighth caption-width step, when the seventh extra step still covers the lead because the lead is wider than that step/);
  assert.match(preview, /that eighth caption-width still covers the lead because the lead is wider than that step/);
  assert.match(preview, /function stepCountEighthCaptionWidthOffEdgeBesideLead/);
  assert.match(preview, /stepCountEighthCaptionWidthOffEdgeBesideLead\(zoom, crop, lead, steppedSeventh\)/);
  assert.match(preview, /Ninth caption-width step, when the eighth extra step still covers the lead because the lead is wider than that step/);
  assert.match(preview, /that ninth caption-width still covers the lead because the lead is wider than that step/);
  assert.match(preview, /function stepCountNinthCaptionWidthOffEdgeBesideLead/);
  assert.match(preview, /stepCountNinthCaptionWidthOffEdgeBesideLead\(zoom, crop, lead, steppedEighth\)/);
  assert.match(preview, /Tenth caption-width step, when the ninth extra step still covers the lead because the lead is wider than that step/);
  assert.match(preview, /that tenth extra step still covers the lead because the lead is wider than that step/);
  assert.match(preview, /function stepCountTenthCaptionWidthOffEdgeBesideLead/);
  assert.match(preview, /stepCountTenthCaptionWidthOffEdgeBesideLead\(zoom, crop, lead, steppedNinth\)/);
  assert.match(preview, /if \(!coversLead\(steppedNinth\)\) return steppedNinth/);
  assert.match(preview, /if \(!coversLead\(steppedTenth\)\) return steppedTenth/);
  assert.match(preview, /Eleventh caption-width step, when the tenth extra step still covers the lead because the lead is wider than that step/);
  assert.match(preview, /that eleventh extra step still covers the lead because the lead is wider than that step/);
  assert.match(preview, /function stepCountEleventhCaptionWidthOffEdgeBesideLead/);
  assert.match(preview, /stepCountEleventhCaptionWidthOffEdgeBesideLead\(zoom, crop, lead, steppedTenth\)/);
  assert.match(preview, /Twelfth caption-width step, when the eleventh extra step still covers the lead because the lead is wider than that step/);
  assert.match(preview, /function stepCountTwelfthCaptionWidthOffEdgeBesideLead/);
  assert.match(preview, /stepCountTwelfthCaptionWidthOffEdgeBesideLead\(zoom, crop, lead, steppedEleventh\)/);
  assert.match(preview, /if \(!coversLead\(steppedTwelfth\)\) return steppedTwelfth/);
  assert.match(preview, /Thirteenth caption-width step, when the twelfth extra step still covers the lead because the lead is wider than that step/);
  assert.match(preview, /function stepCountThirteenthCaptionWidthOffEdgeBesideLead/);
  assert.match(preview, /stepCountThirteenthCaptionWidthOffEdgeBesideLead\(zoom, crop, lead, steppedTwelfth\)/);
  assert.match(preview, /that thirteenth extra step still covers the lead because the lead is wider than that step/);
  assert.match(preview, /Fourteenth caption-width step, when the thirteenth extra step still covers the lead because the lead is wider than that step/);
  assert.match(preview, /function stepCountFourteenthCaptionWidthOffEdgeBesideLead/);
  assert.match(preview, /stepCountFourteenthCaptionWidthOffEdgeBesideLead\(zoom, crop, lead, steppedThirteenth\)/);
  assert.match(preview, /if \(!coversLead\(steppedThirteenth\)\) return steppedThirteenth/);
  assert.match(preview, /that fourteenth extra step still covers the lead because the lead is wider than that step/);
  assert.match(preview, /Fifteenth caption-width step, when the fourteenth extra step still covers the lead because the lead is wider than that step/);
  assert.match(preview, /function stepCountFifteenthCaptionWidthOffEdgeBesideLead/);
  assert.match(preview, /stepCountFifteenthCaptionWidthOffEdgeBesideLead\(zoom, crop, lead, steppedFourteenth\)/);
  assert.match(preview, /if \(!coversLead\(steppedFourteenth\)\) return steppedFourteenth/);
  assert.match(preview, /that fifteenth extra step still covers the lead because the lead is wider than that step/);
  assert.match(preview, /Sixteenth caption-width step, when the fifteenth extra step still covers the lead because the lead is wider than that step/);
  assert.match(preview, /function stepCountSixteenthCaptionWidthOffEdgeBesideLead/);
  assert.match(preview, /stepCountSixteenthCaptionWidthOffEdgeBesideLead\(zoom, crop, lead, steppedFifteenth\)/);
  assert.match(preview, /if \(!coversLead\(steppedFifteenth\)\) return steppedFifteenth/);
  assert.match(preview, /that sixteenth extra step still covers the lead because the lead is wider than that step/);
  assert.match(preview, /Seventeenth caption-width step, when the sixteenth extra step still covers the lead because the lead is wider than that step/);
  assert.match(preview, /function stepCountSeventeenthCaptionWidthOffEdgeBesideLead/);
  assert.match(preview, /stepCountSeventeenthCaptionWidthOffEdgeBesideLead\(zoom, crop, lead, steppedSixteenth\)/);
  assert.match(preview, /if \(!coversLead\(steppedSixteenth\)\) return steppedSixteenth/);
  assert.match(preview, /that seventeenth extra step still covers the lead because the lead is wider than that step/);
  assert.match(preview, /Eighteenth caption-width step, when the seventeenth extra step still covers the lead because the lead is wider than that step/);
  assert.match(preview, /function stepCountEighteenthCaptionWidthOffEdgeBesideLead/);
  assert.match(preview, /stepCountEighteenthCaptionWidthOffEdgeBesideLead\(zoom, crop, lead, steppedSeventeenth\)/);
  assert.match(preview, /if \(!coversLead\(steppedSeventeenth\)\) return steppedSeventeenth/);
  assert.match(preview, /that eighteenth extra step still covers the lead because the lead is wider than that step/);
  assert.match(preview, /Nineteenth caption-width step, when the eighteenth extra step still covers the lead because the lead is wider than that step/);
  assert.match(preview, /function stepCountNineteenthCaptionWidthOffEdgeBesideLead/);
  assert.match(preview, /stepCountNineteenthCaptionWidthOffEdgeBesideLead\(zoom, crop, lead, steppedEighteenth\)/);
  assert.match(preview, /if \(!coversLead\(steppedEighteenth\)\) return steppedEighteenth/);
  assert.match(preview, /if \(!coversLead\(steppedNineteenth\)\) return steppedNineteenth/);
  assert.match(preview, /that nineteenth extra step still covers the lead because the lead is wider than that step/);
  assert.match(preview, /Twentieth caption-width step, when the nineteenth extra step still covers the lead because the lead is wider than that step/);
  assert.match(preview, /function stepCountTwentiethCaptionWidthOffEdgeBesideLead/);
  assert.match(preview, /stepCountTwentiethCaptionWidthOffEdgeBesideLead\(zoom, crop, lead, steppedNineteenth\)/);
  assert.match(preview, /that twentieth extra step still covers the lead because the lead is wider than that step/);
  assert.match(preview, /lead band covers both crop ends so no along-edge gap clears the vertical span/);
  assert.match(preview, /tuck the count one caption-width off that edge into the nearest gap beside the lead/);
  assert.match(preview, /inward \* count\.w/);


  assert.match(preview, /slides along that edge into the first clear gap so the count stays off the art and off the lead/);
  assert.match(preview, /function nudgeSlidCountClearOfStayStamp/);
  assert.match(preview, /shares a span with a stay stamp on that edge/);
  assert.match(preview, /nudges one caption-height further into the gap so it clears the stamp as well as the art/);
  assert.match(preview, /sharing a span with a second stay stamp on that edge/);
  assert.match(preview, /steps one more caption-height into the gap so the count clears both stamps/);
  assert.match(preview, /sharing a span with a third stay stamp on that edge/);
  assert.match(preview, /steps one more caption-height into the gap so the count clears the row of stamps/);
  assert.match(preview, /sharing a span with a fourth stay stamp on that edge/);
  assert.match(preview, /steps one more caption-height into the gap so the count clears the row of stamps/);
  assert.match(preview, /sharing a span with a fifth stay stamp on that edge/);
  assert.match(preview, /sharing a span with a sixth stay stamp on that edge/);
  assert.match(preview, /sharing a span with a seventh stay stamp on that edge/);
  assert.match(preview, /sharing a span with an eighth stay stamp on that edge/);
  assert.match(preview, /sharing a span with a ninth stay stamp on that edge/);
  assert.match(preview, /sharing a span with a tenth stay stamp on that edge/);
  assert.match(preview, /sharing a span with an eleventh stay stamp on that edge/);
  assert.match(preview, /sharing a span with a twelfth stay stamp on that edge/);
  assert.match(preview, /Each new stay stamp on this edge takes one caption-height into the gap/);
  assert.match(preview, /for \(let n = 0; n < 12; n\+\+\)/);
  assert.match(preview, /steps one more caption-height into the gap so the count clears the row of stamps/);
  assert.match(preview, /gap sits off the rail/);
  assert.match(preview, /pin the line to the crop edge nearest that/);
  assert.match(preview, /Esc still clears it early/);
  assert.match(preview, /fit\.lines\.length > 1/);

  assert.match(preview, /seatEdgeCaption\(tick, edge, zoom, crop, label, fit\)/);
  assert.match(preview, /held\.chipLabel/);
  assert.match(preview, /repeats the preview pill/);
  assert.match(preview, /visible end of the commit tick/);
  assert.match(preview, /caption\.label/);
  assert.match(preview, /export function placeAlignPreviewEdgeCaption/);
  assert.match(preview, /edge caption if chip crops/);
  assert.match(preview, /repeats the chip pill/);
  assert.match(preview, /chipOff \? alignEdgeChipLabel\(plan\) : plan\.edge/);
  assert.match(preview, /names key or board/);
  assert.match(preview, /visible end of the preview tick/);
  assert.match(preview, /paintAlignEdgeCaption/);
  assert.match(stage, /drawAlignPreview\(ctx, alignPreview, viewport\.zoom, \{/);
  assert.match(keys, /clearAlignCommitEcho\(\)/);


  assert.match(stage, /drawAlignPreview\(ctx, alignPreview, viewport\.zoom, \{/);
  assert.match(inspector, /Align to key/);
  assert.match(inspector, /data-align-edge/);
  assert.match(inspector, /data-align-stay/);
  assert.match(inspector, /data-align-move/);
  assert.match(inspector, /data-align=/);
  assert.match(inspector, /Commit left/);
  assert.match(inspector, /Align to board/);
  assert.match(inspector, /data-align-board=/);
  assert.match(inspector, /data-align-target=\{target\}/);
  assert.match(inspector, /data-align-target-chip=\{target\}/);
  assert.match(preview, /export function planAlignBoard/);
  assert.match(preview, /Aligned · strip reads \$\{chipLabel\}/);
  assert.match(preview, /Aligned · strip reads \$\{chip\}/);
  assert.match(keys, /commitAlignPreview\(\)/);
  assert.match(keys, /clearAlignPreview\(\)/);
});

test("board left edge shifts a box onto x 0 and pins a box already there", () => {
  const board = { x: 0, w: 200 };
  const mover = { x: 40, w: 20 };
  const stay = { x: 0, w: 10 };
  assert.equal(board.x - mover.x, -40);
  assert.equal(board.x - stay.x, 0);
  assert.match(preview, /target: "board"/);
  assert.match(preview, /Align to board needs an unlocked layer/);
  assert.match(preview, /board edge/);
});

test("left edge keeps the key and shifts the other box", () => {
  const key = { id: "key", x: 40, y: 10, w: 20, h: 20 };
  const other = { id: "other", x: 0, y: 30, w: 10, h: 8 };
  const dx = key.x - other.x;
  assert.equal(dx, 40);
  assert.equal(other.x + dx, key.x);
  assert.match(preview, /key stays/);
  assert.match(preview, /Aligned · strip reads \$\{chipLabel\}/);
  assert.match(preview, /Aligned · strip reads \$\{chip\}/);
});
