import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { test } from "node:test";

const preview = readFileSync(new URL("../src/lib/design/align-preview.ts", import.meta.url), "utf8");
const stage = readFileSync(new URL("../src/components/studio/canvas-stage.tsx", import.meta.url), "utf8");
const inspector = readFileSync(new URL("../src/components/studio/inspector.tsx", import.meta.url), "utf8");
const layers = readFileSync(new URL("../src/components/studio/layers-panel.tsx", import.meta.url), "utf8");
const keys = readFileSync(new URL("../src/components/studio/use-shortcuts.ts", import.meta.url), "utf8");
const studio = readFileSync(new URL("../src/components/studio/studio-app.tsx", import.meta.url), "utf8");

test("align preview draws the key edge before commit", () => {
  assert.match(preview, /export function planAlign/);
  assert.match(preview, /export function drawAlignPreview/);
  assert.match(preview, /First click previews the phosphor edge/);
  assert.match(preview, /expandMovePlaces/);
  assert.match(preview, /"stay" : "key"/);
  assert.match(preview, /keyName/);
  assert.match(preview, /plan\.keyName/);
  assert.match(inspector, /data-align-key-name/);
  assert.match(inspector, /alignEdgeChipLabel/);
  assert.match(inspector, /data-align-preview-chip=\{alignEdgeChipLabel\(live\)\}/);
  assert.match(inspector, /data-align-preview-line/);
  assert.match(inspector, /Same chip as the layers row/);
  assert.match(preview, /plan\.edge} edge/);
  assert.match(preview, /export function placeAlignEdgeChip/);
  assert.match(preview, /clear of stay boxes/);
  assert.match(preview, /alignEdgeChipLabel/);
  assert.match(preview, /\$\{plan\.edge\} · \$\{who\}/);
  assert.match(preview, /hang the longer/);
  assert.match(preview, /plan\.edge === "left"/);
  assert.match(preview, /plan\.edge === "bottom"/);
  assert.match(preview, /export function placeAlignStayStamp/);
  assert.match(preview, /stay box corner/);
  assert.match(preview, /stamp\.label/);
  assert.match(preview, /edge === "middle"/);
  assert.match(preview, /edge === "center"/);
  assert.match(preview, /export function holdAlignCommitEcho/);
  assert.match(preview, /export function drawAlignCommitEcho/);
  assert.match(preview, /export function alignCommitEchoAlpha/);
  assert.match(preview, /eases to 0/);
  assert.match(preview, /ctx.globalAlpha = alpha/);
  assert.match(preview, /stamp holds on/);
  assert.match(preview, /edge tick fades with it/);
  assert.match(preview, /export function placeAlignCommitEdgeTick/);
  assert.match(preview, /held\.edgeTick/);
  assert.match(preview, /placeAlignStayStamp\(g, held\.edge, zoom\)/);
  assert.match(stage, /drawAlignCommitEcho\(ctx, alignEcho, viewport\.zoom/);
  assert.match(preview, /export function placeAlignCommitEdgeCaption/);
  assert.match(preview, /caption if stamp crops names key or board and fades with the stamp/);
  assert.match(preview, /export function noteAlignCommitFadeCaption/);
  assert.match(preview, /alignCommitFadeAppend\(pill, echo.moveCount\)/);
  assert.match(preview, /fade \$\{pill\} · \$\{moveCount\} move/);
  assert.match(preview, /strip reads \$\{chip\}/);
  assert.match(preview, /const chip = alignEdgeChipLabel\(plan\)/);
  assert.match(studio, /StudioStatusStrip/);
  assert.match(preview, /baseStatus/);
  assert.match(preview, /fadingPill/);
  assert.match(preview, /rail and the strip agree/);
  assert.match(preview, /fadePill/);
  assert.match(preview, /moveCount: boxes.length/);
  assert.match(inspector, /data-align-commit-line/);
  assert.match(inspector, /data-align-commit-pill/);
  assert.match(inspector, /echo.fadePill/);
  assert.match(preview, /moverIds/);
  assert.match(preview, /each mover's layers row/);
  assert.match(layers, /data-layer-align-pill/);
  assert.match(layers, /alignEcho\?\.moverIds.includes/);
  assert.match(layers, /subscribeAlignCommitEcho/);
  assert.match(preview, /export function alignPreviewMoverIds/);
  assert.match(preview, /Stay rows stay unmarked/);
  assert.match(layers, /subscribeAlignPreview/);
  assert.match(layers, /alignPreviewMoverIds\(alignPreview\)/);
  assert.match(layers, /data-layer-align-preview=/);
  assert.match(layers, /data-layer-align-preview-mover/);
  assert.match(layers, /alignEdgeChipLabel\(alignPreview\)/);
  assert.match(layers, /Edge chip while align preview is armed/);
  assert.match(inspector, /alignCommitLayerFadeLine\(echo.chipLabel, echo.fadePill, echo.moveCount\)/);
  assert.match(inspector, /data-align-commit-chip=\{echo.chipLabel\}/);
  assert.match(inspector, /alignCommitSolidLead\(echo.chipLabel, echo.moveCount\)/);
  assert.match(inspector, /Same truncated chip and move count the status strip leads with/);
  assert.match(preview, /alignCommitSolidLead/);
  assert.match(preview, /\$\{lead\} · Aligned · strip reads \$\{chipLabel\}/);
  assert.match(layers, /alignCommitSolidLead\(alignEcho\.chipLabel, alignEcho\.moveCount\)/);
  assert.match(layers, /alignCommitLayerFadeLine/);
  assert.match(layers, /data-layer-align-fade/);
  assert.match(preview, /export function alignCommitLayerFadeLine/);
  assert.match(preview, /each mover row keeps/);
  assert.match(inspector, /The fade pill can still append after it/);
  assert.match(inspector, /appends the cropped pill with the same move count the layers row and status strip show/);
  assert.match(preview, /export function alignCommitFadeAppend/);


  assert.match(preview, /releases with the beat/);
  assert.match(preview, /paintAlignEdgeCaption\(ctx, caption, z, alpha\)/);
  assert.match(preview, /chipLabel/);
  assert.match(preview, /stampsOff && releaseLine \? releaseLine : stampsOff && chipLabel \? chipLabel : edge/);
  assert.match(preview, /alignCommitLayerFadeLine\(held\.chipLabel, held\.chipLabel, held\.moveCount\)/);
  assert.match(preview, /repeats the same release line/);
  assert.match(preview, /wider than the rail/);
  assert.match(preview, /shrinks the type or wraps once rather than clipping the move count/);
  assert.match(preview, /only partly on the rail still names the full line/);
  assert.match(preview, /function fitAlignCommitCaption/);
  assert.match(preview, /function wrapReleaseLineOnce/);
  assert.match(preview, /function seatWrappedCommitCaption/);
  assert.match(preview, /seats clear of the landed boxes/);
  assert.match(preview, /status strip keeps the unwrapped release line/);
  assert.match(preview, /function openCropEndAlong/);
  assert.match(preview, /rail clamp pulls that two-line pill back onto a short mover/);
  assert.match(preview, /slides to the open end of the crop so the move count stays off the art/);
  assert.match(preview, /both crop ends are blocked/);
  assert.match(preview, /tucks the move-count line into the nearest gap beside the short mover/);
  assert.match(preview, /function tuckMoveCountBesideShortMover/);
  assert.match(preview, /tuckedMoveCount/);
  assert.match(preview, /When that gap sits off the rail, the tucked line pins to the crop edge nearest that mover/);
  assert.match(preview, /function pinTuckedCountToNearestCropEdge/);
  assert.match(preview, /function swapPinnedCountOffSharedCropEdge/);
  assert.match(preview, /share the crop edge nearest the short mover/);
  assert.match(preview, /swaps the count to the other crop edge so the two lines do not stack/);
  assert.match(preview, /function slideSwappedCountAlongBlockedEdge/);
  assert.match(preview, /slides along that edge into the first clear gap so the count stays off the art and off the lead/);
  assert.match(preview, /function nudgeSlidCountClearOfStayStamp/);
  assert.match(preview, /shares a span with a stay stamp on that edge/);
  assert.match(preview, /nudges one caption-height further into the gap so it clears the stamp as well as the art/);
  assert.match(preview, /sharing a span with a second stay stamp on that edge/);
  assert.match(preview, /steps one more caption-height into the gap so the count clears both stamps/);
  assert.match(preview, /sharing a span with a third stay stamp on that edge/);
  assert.match(preview, /steps one more caption-height into the gap so the count clears the row of stamps/);
  assert.match(preview, /sharing a span with a fourth stay stamp on that edge/);
  assert.match(preview, /steps one more caption-height into the gap so the count clears the row of stamps/);
  assert.match(preview, /sharing a span with a fifth stay stamp on that edge/);
  assert.match(preview, /sharing a span with a sixth stay stamp on that edge/);
  assert.match(preview, /const sixth = overlapping\(penta\)/);
  assert.match(preview, /steps one more caption-height into the gap so the count clears the row of stamps/);
  assert.match(preview, /gap sits off the rail/);
  assert.match(preview, /pin the line to the crop edge nearest that/);
  assert.match(preview, /Esc still clears it early/);
  assert.match(preview, /fit\.lines\.length > 1/);

  assert.match(preview, /seatEdgeCaption\(tick, edge, zoom, crop, label, fit\)/);
  assert.match(preview, /held\.chipLabel/);
  assert.match(preview, /repeats the preview pill/);
  assert.match(preview, /visible end of the commit tick/);
  assert.match(preview, /caption\.label/);
  assert.match(preview, /export function placeAlignPreviewEdgeCaption/);
  assert.match(preview, /edge caption if chip crops/);
  assert.match(preview, /repeats the chip pill/);
  assert.match(preview, /chipOff \? alignEdgeChipLabel\(plan\) : plan\.edge/);
  assert.match(preview, /names key or board/);
  assert.match(preview, /visible end of the preview tick/);
  assert.match(preview, /paintAlignEdgeCaption/);
  assert.match(stage, /drawAlignPreview\(ctx, alignPreview, viewport\.zoom, \{/);
  assert.match(keys, /clearAlignCommitEcho\(\)/);


  assert.match(stage, /drawAlignPreview\(ctx, alignPreview, viewport\.zoom, \{/);
  assert.match(inspector, /Align to key/);
  assert.match(inspector, /data-align-edge/);
  assert.match(inspector, /data-align-stay/);
  assert.match(inspector, /data-align-move/);
  assert.match(inspector, /data-align=/);
  assert.match(inspector, /Commit left/);
  assert.match(inspector, /Align to board/);
  assert.match(inspector, /data-align-board=/);
  assert.match(inspector, /data-align-target=\{target\}/);
  assert.match(inspector, /data-align-target-chip=\{target\}/);
  assert.match(preview, /export function planAlignBoard/);
  assert.match(preview, /Aligned · strip reads \$\{chipLabel\}/);
  assert.match(preview, /Aligned · strip reads \$\{chip\}/);
  assert.match(keys, /commitAlignPreview\(\)/);
  assert.match(keys, /clearAlignPreview\(\)/);
});

test("board left edge shifts a box onto x 0 and pins a box already there", () => {
  const board = { x: 0, w: 200 };
  const mover = { x: 40, w: 20 };
  const stay = { x: 0, w: 10 };
  assert.equal(board.x - mover.x, -40);
  assert.equal(board.x - stay.x, 0);
  assert.match(preview, /target: "board"/);
  assert.match(preview, /Align to board needs an unlocked layer/);
  assert.match(preview, /board edge/);
});

test("left edge keeps the key and shifts the other box", () => {
  const key = { id: "key", x: 40, y: 10, w: 20, h: 20 };
  const other = { id: "other", x: 0, y: 30, w: 10, h: 8 };
  const dx = key.x - other.x;
  assert.equal(dx, 40);
  assert.equal(other.x + dx, key.x);
  assert.match(preview, /key stays/);
  assert.match(preview, /Aligned · strip reads \$\{chipLabel\}/);
  assert.match(preview, /Aligned · strip reads \$\{chip\}/);
});
